# Site settings
title: "Resumen de un desarrollador web"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Imanol U. Tamayo."
resume_title:                   "Ingeniero en sistemas con enfoque en desarrollo de aplicaciones."

# used for the contact button in _layouts/resume.html
resume_contact_email:           "imanol1836@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Mi nombre es Imanol Ucan, y soy un apasionado programador web con una profunda afinidad por el mundo digital. Desde mi temprana adolescencia, mi fascinación por la tecnología y la creatividad me condujo a explorar el vasto universo de la programación. Desde entonces, mi viaje en el desarrollo web ha sido una emocionante odisea de aprendizaje constante y experimentación.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
remove the resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience: "<p>DigitalWeb Innovations,- Desarrollador Web Junior. En DigitalWeb Innovations, comencé mi carrera como Desarrollador Web Junior, donde adquirí una base sólida en programación web y me sumergí en el mundo del desarrollo de sitios web. Algunas de mis responsabilidades y logros durante mi tiempo en esta empresa fueron: |Desarrollo Front-end: Creé sitios web atractivos y funcionales utilizando HTML, CSS y JavaScript, asegurándome de que fueran compatibles con múltiples navegadores y dispositivos|  |Soporte Técnico: Brindé soporte técnico a los usuarios finales, solucionando problemas y realizando actualizaciones cuando fuera necesario.|</p>" 
resume_section_education:       true
#resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
 # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
